### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hotsu0p** [Bumer-32/Redstone-Helper#4]
How do you build the mod?

**Comment by hotsu0p** [comment]
like which task is it

**Comment by Bumer-32** [comment]
Tasks/fabric/runClient
![зображення](https://github.com/Bumer-32/Redstone-Helper/assets/79054301/a230c1ee-8717-4d4f-a7ad-ee95b8db2dd8)

**Comment by hotsu0p** [comment]
alr
